# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: List files (for debugging)
      run: ls -R
    # 上传依赖到github,不需要
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    # 部署包
    #- name: ssh scp ssh pipelines
    #  uses: cross-the-world/ssh-scp-ssh-pipelines@latest
    #  env:
    #    WELCOME: "ssh scp ssh pipelines"
    #    LASTSSH: "Doing something after copying"
    #  with:
    #    host: ${{ secrets.CLZ_HOST }}
    #    user: ${{ secrets.CLZ_USER }}
    #    pass: ${{ secrets.CLZ_PASS }}
    #    port: 22
    #    connect_timeout: 10
    #    first_ssh: |
    #      rm -rf /var/www/html/action_practise/*
    #    scp: |
    #      './dist/*' => /var/www/html/action_practise/


      # 5. 上传 jar 包到远程服务器
    - name: Deploy JAR via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # 服务器SSH私钥
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}         # 服务器IP
        REMOTE_USER: ${{ secrets.REMOTE_USER }}         # 服务器用户名
        JAR_NAME:  ./eladmin-system/target/*.jar                      
        REMOTE_DIR: /home/ecs-user/Jem-test
      run: |
        # 安装 ssh-agent 并添加私钥
        sudo apt-get install -y openssh-client
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # 禁用主机密钥检查（首次连接避免交互提示）
        echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null" > ~/.ssh/config
        echo -e "hello world" >/dev/null
        #ls $JAR_NAME
        pwd && ls
        ls ./eladmin-system/*
        echo "Runner IPv4: $(curl -s ifconfig.me)"
        #ls target/*
        # 上传 jar 包
        #scp -r $JAR_NAME $REMOTE_USER@$REMOTE_HOST:$REMOTE_DIR/

        # 可选：重启服务（例如Spring Boot）
        #ssh $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_DIR && ls -al && echo 'Deploy completed!'"
